SainsburyWellcomeCentre/crabs-exploration

bboxes labelling/ManualLabellingSteps.md
A readme compiling the instructions on how to do manual labelling for a multi-crab detector
=> add manual labelling steps

stereo calibration/CalibrationDataCollection.md
After a bit of research, I collected a few recommendations on how to best collect calibration data for a stereo camera configuration.
=> Recommendations for collecting calibration data

stereo calibration/CalibrationDataCollection.md
small final additions to the calibration data collection guidelines
=> small addition to guidelines

bboxes labelling/ExtractFramesCluster.md
A HowTo guide to run a frame extraction job in the SWC cluster
=> Frame extraction in the cluster

pose estimation/cluster bash scripts/howto_training_cluster.md
I merged the PR too quickly and missed one of the reviewer's comments, sorry! 😇
=> Fix typo in guide

LICENSE
BSD-3 is the SWC ARC agreed in the ways of working.
=> Add BSD-3 license.

crabs/stereo_calibration/__init__.py, crabs/stereo_calibration/extract_pairs_of_frames.py, notebooks/notebook_detect_chessboard_in_sampled_frames.py, notebooks/notebook_detect_chessboard_in_video.py, notebooks/notebook_timecodes.py
I merged too soon! 🙉 
Forgot to push these... I blame lunch break
=> Small additions to timecodes matching

README.md, crabs/detection_tracking/train_model.py, pyproject.toml
- add readme on how to run mlflow
- add experiment name 
- add log hyper parameters
=> cleaned up mlflow and add readme

.github/workflows/test_and_deploy.yml
Perhaps fixes our [broken Codecov uploads](https://github.com/SainsburyWellcomeCentre/crabs-exploration/actions/runs/8435603997/job/23101404604#step:2:320). [Following the NIU documentation](https://github.com/neuroinformatics-unit/actions/tree/main/test#python-test-action).
=> Add Codecov token.

tests/test_unit/test_tracking_utils.py
A quick fix to the path of the test data.
=> Fix path in tracking utils tests 

crabs/detection_tracking/datamodules.py
We were passing the transforms of the training set to all other sets.
With this fix we pass the test transforms to the validation set and the test set.
Feels a bit overkill to compute all three splits every time, but to use `random_split` we need to pass a dataset with transforms already linked to it. Open to suggestions for a nicer way 👀 .
Also: how could we make a test for this?
=> Fix transforms passed to each dataset split

crabs/detection_tracking/datamodules.py
Following Lightning suggestion ⚡
=> Set persistent workers for validation dataloader

README.md, crabs/detection_tracking/evaluate_model.py, crabs/detection_tracking/train_model.py, pyproject.toml, tests/test_unit/test_entry_points.py
- Updated readme
- Updated entry point test
- Small edits to CLI help to include default values
=> Create entry point for evaluate model

crabs/detection_tracking/train_model.py
Log the Slurm ID, and set the run_name in MLFlow as the Slurm ID
=> add slurm id logging

crabs/detection_tracking/train_model.py
Two fixes:
- Fix slurm ID for array jobs: I was using the individual ID rather than the parent ID
- Fix artifact from rebase: I rebased to main using Github interface and didn't check carefully the result.... the logging code was duplicated, I thought I was going crazy 😅
=> fix slurm ID for array jobs

crabs/detection_tracking/config/faster_rcnn.yaml
Clarify options for artifact saving
=> Add possible values for artifact saving parameter in faster_rcnn.yaml

tests/test_unit/test_tracking_utils.py
Parametrising test for counting ID switches
=> ID switch test parametrisation

crabs/detection_tracking/train_model.py
I guess, when we merged 2 PRs yesterday, some lines were accidentally deleted. The one from resume training from weights only checkpoint
=> Fix missing line

crabs/detection_tracking/train_model.py
odd things happened yesterday while merging? 🙀
=> Fix duplicate line

MANIFEST.in, notebooks/notebook_fix_annotations_file.py, notebooks/notebook_overlay_video.py, notebooks/notebook_trajectories_movement.py, notebooks/script_opencv_video.py, scripts/output_video.py
Add notebooks for:
- inspecting trajectories with `movement` 
- generating a video overlay
- fixing duplicates in annotations file
Also added a helper script to generate overlaid videos for inspection.
=> Add notebooks for inspecting trajectories

bash_scripts/run_training_array.sh, bash_scripts/run_training_single.sh
- Use source activate rather than conda activate in hpc
- Remove source bashrc
=> Update bash scripts for training in the cluster

bash_scripts/run_training_array_subset_annotations.sh
**What is this PR?**
**Why is this PR needed?**
**What does this PR do?**
Please reference any existing issues/PRs that relate to this PR.
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
If any features have changed, or have been added. Please explain how the
documentation has been updated.
=> Bash script to remove small annotations and retrain
