SainsburyWellcomeCentre/crabs-exploration

bboxes labelling/extract_frames_to_label_w_sleap.py
bboxes labelling/run_frame_extraction.sh

In pipeline for extracting frames to label:
- I changed the input directory argument to take a list of directories or specific video files
- I changed the naming of the extracted frames, so that the name of the camera (i.e., the videos parent dir) and the name of the video file are included in the name of the frame extracted. This way we retain this information when we export the labels in COCO format.
- I changed the prints to logging module calls

change input dir to list of video locations (can be dirs or files)

---

bboxes labelling/ManualLabellingSteps.md

Small additions to the labelling steps instructions after a first run
- add a pair of useful shortcuts
- add a note about the project name shown when a project is re-loaded

Minor additions to labelling steps

---

crabs/detection_tracking/train_model.py
pyproject.toml
tests/test_unit/test_entry_points.py

Allows for a more succinct syntax independent of the cwd:
```
train-detector --dataset-dirs /path/to/dataset
```
vs before, we needed to run the following from the repo root:
```
python crabs/detection_tracking/train_model.py --dataset-dirs /path/to/dataset
```

Define entry point for training the detector

---

crabs/detection_tracking/datamodules.py
crabs/detection_tracking/evaluate_model.py

We removed the `stage` parameter from the datamodule setup. We now compute the train, validation and test splits everytime a datamodule instance is created.

Remove stage from datamodule setup

---

crabs/detection_tracking/datamodules.py
crabs/detection_tracking/evaluate_model.py

We need to keep the `stage` argument in the setup of the datamodule, as it seems to be used internally. Otherwise we get:
```
TypeError: CrabsDataModule.setup() got an unexpected keyword argument 'stage'
```
Since it doesn't have a default value, in the eval module we also need to specify it when we call `setup` directly.

Recover stage argument in setup for datamodule

---

crabs/detection_tracking/config/faster_rcnn.yaml
crabs/detection_tracking/detection_utils.py
crabs/detection_tracking/models.py
crabs/detection_tracking/train_model.py

The `.log` function cannot force the api to log for every epoch even when set `on_epoch=True` and `on_step=False`.
[Seems like unresolved issue](https://github.com/Lightning-AI/pytorch-lightning/issues/3228).
Instead we do `.log_metric` and set `step=self.current_epoch`. The x-axis will say step but it is in epoch.
Few other small changes:
- log model_filename in the mlflow
- options for fast debugging:
1. `fast_dev_run` only run for one batch and one epoch.
2. `limit_train_batches` run every epochs with limited percentage of training data.

Changes the log to log every epoch

---

crabs/detection_tracking/datamodules.py

Right now we first need to create the dataset and then split it. The transforms are unfortunately defined when creating the dataset (there may be ways around this but haven't digged into it).
Since validation and test set will always have the same transforms, we reduce the repeated dataset generation by computing them in one go.

Compute test and validation splits in one go using the same transforms

---

crabs/detection_tracking/train_model.py
tests/test_unit/test_train_model.py

It should be imported from detection_utils (but it's actually not used here so I just deleted it)

Remove DEFAULT_ANNOTATIONS_FILENAME definition in train script

---

crabs/detection_tracking/train_model.py

By default, the mlflow will write to `/ceph/zoo/users/sminano/ml-runs`.
For debugging or running locally, 
set `--mlflow_folder "./ml-runs"`

changes to default mlflow folder

---

bash_scripts/run_training_array.sh
bash_scripts/run_training_single.sh
crabs/detection_tracking/train_model.py

This PR fixes the utf-8 encoding error we were getting with MLflow logger. 
The path passed needs to be a 'raw' string (the forward slashes need to be escaped).
I also changed the default location for the `ml-runs` to be under the current working directory. When we launch a job in the cluster (using `run_training....sh`), I set the MLflow folder argument to be the one we agreed in ceph. Let me know thoughts, I think this would be the most convenient.
I checked this fix works: locally, with an interactive node, with a batch job.

Fix MLflow folder error

---

crabs/detection_tracking/train_model.py

A much better fix (that actually works 😅 )
To check:
1. Connect to SWC HPC and git clone the repo
2. Edit `bash_scripts/run_training_single.sh` temporarily:
- to install the crab package with the version of this branch (`smg/fix-paths-mlflow-folder`, line 46)
- (optional): edit `--mlflow_folder` (line 98) to point to a location where you can quickly check if it's created
- (optional): add `--limit_train_batches 0.01` and edit the config to run for 1 epoch only
3. Launch the job with `sbatch bash_scripts/run_training_single.sh`
4. It should create an `ml-run` folder where it was told

Fix MLflow folder issue with pathlib

---

bash_scripts/run_training_array.sh
bash_scripts/run_training_single.sh

To be a bit more consistent with the training jobs we run, we agreed to have a common `ml-runs` folder. 
However, during development we often do debugging runs. For that it seems useful to have a "scratch" `ml-runs` folder.
I propose the following structure:
Under `/ceph/zoo/users/sminano/ml-runs-all` we have:
- `ml-runs-scratch` to hold temp runs, which we can regularly empty with no fear.
- `ml-runs`, where we hold the training jobs that we want to consider for evaluation
- any other useful / backup old runs we want (for example right now `ml-runs-sminano-copy`)
The idea is that we launch training jobs in the cluster identically, i.e., both of us using the bash script from the repo (preferably the job array one for jobs we want to consider for evaluation).
In this PR, I set the …

Proposed structure for `ml-run`

---

crabs/detection_tracking/train_model.py

To keep all together, this PR adds the slurm logs to the MLflow run artifacts.
The slurm logs filename format is assumed to be the one set in the training bash scripts.
1. Connect to the SWC HPC and git clone this repo (for example in your `scratch` space).
1. Edit `bash_scripts/run_training_single.sh` to:
- install the version of the crabs package from this branch (`smg/add-slurm-logs-as-artifacts`, line 46)
- add these two lines at the end:
```
--mlflow_folder /ceph/zoo/users/sminano/ml-runs-all/ml-runs-scratch \
--limit_train_batches 0.01
```
1. Run `sbatch bash_scripts/run_training_single.sh`
1. Activate a conda environment with `mlflow` and run 
```
mlflow ui --backend-store-uri file:////ceph/zoo/users/sminano/ml-runs-all/ml-runs-scratch
``` 
1. When the training job is complete, the …

Add slurm logs as mlflow artifacts

---

crabs/detection_tracking/detection_utils.py
crabs/detection_tracking/evaluate_model.py
crabs/detection_tracking/train_model.py

This PR moves some of the MLflow logger setup functions to `detection_utils`, so that they are shared in the training and eval script.

Refactor mlflow logger setup to re-use in evaluation

---

crabs/detection_tracking/detection_utils.py
crabs/detection_tracking/evaluate_model.py
crabs/detection_tracking/train_model.py

This PR comes from work in PR #136 and suggests a refactoring of the `setup_loggers` functions that keeps the structure of `train_model.py` and `evaluate_model.py` consistent.
It defines:
1-  a `setup_logger_with_checkpointing` function in `detection_utils.py` that defines a logger with checkpointing.
2- a `setup_logger_without_checkpointing` function in `detection_utils.py` for a logger without checkpointing.
3- then we import these functions in `train_model.py` and `evaluate_model.py` for their specific `self.setup_logger()` methods. (And we can import that in the optuna code too in the future #188 )

Refactor setup of loggers

---

crabs/detection_tracking/detection_utils.py
crabs/detection_tracking/train_model.py

Following suggestions from a similar code review, this PR
- moves the computation of the checkpoint type to `detection_utils`,
- refactors the main training script to reduce length.
Let me know what you think!
thanks 🙌

Small refactoring to load from ckpt

---

crabs/tracker/config/tracking_config.yaml
crabs/tracker/track_video.py
crabs/tracker/utils/io.py
crabs/tracker/utils/tracking.py
tests/test_unit/test_tracking_utils.py

Adding prediction score during tracking inference to csv file. At the moment to VIA format csv, should we have simple csv option, if we not intend to do tracking labelling?

adding scores

---

crabs/detector/train_model.py

I think we need to set `log=True` so that we sample the learning rate from the log space.

Optuna fix: sample learning rate from log domain

---

bash_scripts/run_evaluation_array.sh
guides/EvaluatingModelsHPC.md

- Adds a bash scrip to run an array job in SLURM to evaluate a list of models.
- The syntax allows to evaluate all the epoch checkpoints of a model, or the same epoch checkpoint for a range of MLflow runs. 	
- Add a guide.

Bash script for an evaluation array job

---

crabs/detector/evaluate_model.py
crabs/detector/train_model.py
crabs/detector/utils/detection.py
tests/test_unit/test_optuna.py
tests/test_unit/test_train_model.py

Small edits to training to better match evaluation.
- factors out logging to screen of MLflow info and datasets info
- fixes typo in Detector class name
- CLI arguments review: reorder them to be more consistent across evaluation and training

Small edits to training

---

crabs/tracker/evaluate_tracker.py
crabs/tracker/track_video.py
crabs/tracker/utils/io.py
crabs/tracker/utils/tracking.py
tests/test_unit/test_evaluate_tracker.py
tests/test_unit/test_track_video.py
tests/test_unit/test_tracking_io.py
tests/test_unit/test_tracking_utils.py

**What is this PR?**
**Why is this PR needed?**
- Review of part of the work from #180 
**What does this PR do?**
- Factors out and makes the steps in the detect+track pipeline more modular.
- Removes some code duplications (e.g. when preparing data for sort, formating the detections dict...)
- Reviews typing and docstrings
- Adapts current tests to the changes
- Same MOTA on GT clip as reference -- planned integration tests for next PR.
Work focuses mostly on the detect+track pipeline, as the tracker evaluation will be covered in a separate PR.
#180 
Integration run manually on reference clip. Existing tests pass locally.
No.
- [ n/a ] The documentation has been updated to reflect any changes

Refactored detection+tracking

---

guides/ManualLabellingSteps.md

**What is this PR?**
Ensures the category ID entered is a number, so that the COCO export works correctly.
**Why is this PR needed?**
When following the steps, the data exported in COCO format produced a `null` category.
This is because COCO does not accept a string category ID (but VIA does).
**What does this PR do?**
Clarifies in the labelling guide that the category ID needs to be an integer
[this issue](https://gitlab.com/vgg/via/-/issues/296) from the VIA tool
Separately using the VIA tool.
It is an update of the existing guides.
- [ n/a ] The code has been tested locally
- [ n/a ] Tests have been added to cover all new functionality

Add steps to avoid category ID null when exporting as COCO in VIA
